name: Secure Config

on: [push]

jobs:
  config:
    runs-on: ubuntu-latest
    env:
      APP_ENV: production   # normal env variable

    steps:
      - name: Combine secret + env
        run: |
          echo "Environment is $APP_ENV"
          echo "Password is ${{ secrets.DB_PASSWORD }}"